version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8000"
        depends_on:
            - mysql
        volumes:
            - ./public/img:/var/www/html/public/img
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: library
        ports:
            - "3306:3306"
